{
 "title": "Node Summary",
 "description": "【中文版本】2020.05.30更新，增加整体资源展示！支持 Grafana6&7，Node Exporter v0.16及以上的版本，优化重要指标展示。包含整体资源展示与资源明细图表：CPU 内存 磁盘 IO 网络等监控指标。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "node count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_uname_info - 0)" }
   ]
  },
  {
   "title": "avg time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - avg(node_boot_time_seconds{})"
    }
   ]
  },
  {
   "title": "memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system'})"
    }
   ]
  },
  {
   "title": "disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0)"
    }
   ]
  },
  {
   "title": "summary",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "node_uname_info - 0" },
    { "expr": "node_memory_MemTotal_bytes - 0" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds)by(instance)"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  }
 ]
}