{
 "title": "监控大盘",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "请求总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service=~\"gateway.matrix.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"gateway\",destination_workload_namespace=\"matrix\"}[5m])) "
    }
   ]
  },
  {
   "title": "2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service=~\"gateway.matrix.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"gateway\",destination_workload_namespace=\"matrix\",response_code=~\"2.*\"}[5m])) "
    }
   ]
  },
  {
   "title": "响应成功率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service=~\"gateway.matrix.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"gateway\",destination_workload_namespace=\"matrix\",response_code=~\"[234][0-9]{2}\"}[5m])) / sum(irate(istio_requests_total{destination_service=~\"gateway.matrix.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"gateway\",destination_workload_namespace=\"matrix\",response_code=~\".*\"}[5m])) "
    }
   ]
  },
  {
   "title": "响应成功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service=~\"gateway.matrix.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"gateway\",destination_workload_namespace=\"matrix\",response_code=~\"[234][0-9]{2}\"}[5m])) / sum(irate(istio_requests_total{destination_service=~\"gateway.matrix.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"gateway\",destination_workload_namespace=\"matrix\",response_code=~\".*\"}[5m])) "
    }
   ]
  },
  {
   "title": "Gateway QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_workload_namespace=\"matrix\",reporter=~\"destination\",destination_service=~\"gateway.matrix.svc.cluster.local\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  { "title": "Pod 状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Deployment 副本数 ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_deployment_status_replicas{exported_namespace=\"matrix\"})"
    }
   ]
  },
  {
   "title": "Deployment 副本数 增减数（15m内差值）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{exported_namespace=~\"matrix\"}) - sum(kube_deployment_status_replicas{exported_namespace=~\"matrix\"}offset 15m)",
     "legendFormat": "增长副本数"
    },
    {
     "expr": "(sum(kube_deployment_status_replicas{namespace=~\"matrix\"})/sum(kube_deployment_status_replicas{namespace=~\"matrix\"}offset 15m) -1)*100",
     "legendFormat": "增长百分比"
    }
   ]
  },
  {
   "title": "POD 异常总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"matrix\", phase=~\"Pending|Failed|Unknown\"})"
    },
    {}
   ]
  },
  {
   "title": "Containers Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (  (kube_pod_container_status_restarts_total{ pod_name=~\".*\",exported_namespace=\"matrix\"} ))"
    }
   ]
  },
  {
   "title": "POD Pending 总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=\"matrix\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "POD Unknown 总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"matrix\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "资源用量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"chatie-services-.+\",namespace=\"matrix\"}[1m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}