apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: details
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: productpage
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ratings
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: reviews
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/hostname: bookinfo.cloudnative.love
    external-dns.alpha.kubernetes.io/ttl: "120"
