apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cassandra-exporter
  monitor: prometheus

#commonAnnotations:
#  prometheus.io/path: /metrics
#  prometheus.io/port: "5557"
#  prometheus.io/scrape: "true"

resources:
- all.yaml

#images:
#- name: danielqsj/cassandra-exporter
#  newTag: latest