apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-istiod
  labels:
    release: prometheus
spec:
  jobLabel: my-istio
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      istio: pilot
  endpoints:
    - interval: 10s
      path: /metrics
      port: http-monitoring
  # endpoints:
  #   - port: http-monitoring
  #     interval: 15s
  #     relabelings:
  #       - sourceLabels:
  #           [
  #             __meta_kubernetes_service_name,
  #             __meta_kubernetes_endpoint_port_name,
  #           ]
  #         action: keep
  #         regex: istiod;http-monitoring
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: istio-ingressgateway
#   labels:
#     release: prometheus
# spec:
#   jobLabel: my-istio
#   selector:
#     matchLabels:
#       istio: ingressgateway
#   namespaceSelector:
#     matchNames:
#       - istio-system
#   endpoints:
#     - targetPort: http-envoy-prom
#       path:
#         /stats/prometheus

#         # - name: http-envoy-prom  # 用于Prometheus的端口
#         #   port: 15090  # Envoy统一暴露Prometheus指标的端口
#         #   targetPort: 15090
#         #   protocol: TCP
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: istio-sidecars-monitor
#   labels:
#     monitoring: istio-sidecars
#   namespace: istio-system
# spec:
#   jobLabel: my-istio
#   selector:
#     matchLabels:
#       security.istio.io/tlsMode: "istio"
#   podMetricsEndpoints:
#     - port: http-envoy-prom
#       path: /stats/prometheus
#       interval: 15s
# https://discuss.istio.io/t/scraping-istio-metrics-from-prometheus-operator-e-g-using-servicemonitor/10632/2
# https://prune998.medium.com/prometheus-operator-and-istio-telemetry-v2-8be5e073272
