apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: production

commonAnnotations:
  armsPilotAutoEnable: "on"
  armsPilotCreateAppName: matrix-lanling-services-prod
  #msePilotAutoEnable: "on"
  #msePilotCreateAppName: matrix-lanling-services-prod

resources:
- ../../base

patchesStrategicMerge:
- patch.yaml

images:
- name: registry-vpc.cn-hangzhou.aliyuncs.com/yizhoucp/lanling-services
  newName: docker-registry-vpc.myrightone.com/matrix-world/lanling-services
  newTag: release-504a621d
