apiVersion: kustomize.config.k8s.io/v1beta1
kind: HelmChartInflationGenerator
metadata:
  name: mychart
helmCharts:
  - name: my-example
    releaseName: my-release
    repo: https://SJFCS.github.io/DevOpsConfig
    version: 0.2.0
    namespace: default
    valuesFile: values.yaml
