kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "avp/data/account"
type: Opaque
stringData:
  username: <path:secret/data/database#username>
  password: <path:secret/data/database#password>
