kind: Secret
apiVersion: v1
metadata:
  name: vault-example
  annotations:
    # avp.kubernetes.io/path: "secret/data/database"
    avp.kubernetes.io/path: "avp/data/account"
    avp.kubernetes.io/secret-version: "2" # 2 is the latest revision in this example
type: Opaque
data:
  username: <username>
  password: <password>
  username-current: <path:secret/data/database#username#2> # same as <username>
  password-current: <path:secret/data/database#password#2> # same as <password>
  username-old: <path:secret/data/database#username#1>
  password-old: <path:secret/data/database#password#1>
