---
# Source: prometheus/templates/server/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
---
# Source: prometheus/templates/server/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: istio-system
data:
  alerting_rules.yml: |
    groups:
    - name: hostStatsAlert
      rules:
      # 内存
      - alert: "Linux 内存使用率高"
        # 内存剩余容量小于 12% 且小于 5GB
        expr: instance:node_memory_utilisation:ratio{} *100 > 85
          and (node_memory_MemAvailable_bytes{} / 1024 / 1024 / 1024) < 5
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} 内存使用率高"
          description: "{{ $labels.instance }} 内存使用率高于 85% (当前值: {{ $value }})"
      # CPU
      - alert: "CPU 使用率高"
        expr: instance:node_cpu_utilisation:rate5m{} *100 > 85
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} CPU 使用率高"
          description: "{{ $labels.instance }} CPU 使用率高于 85% (当前值: {{ $value }})"
      # 磁盘
      - alert: "节点磁盘使用率高"
        expr: 100 - (node_filesystem_free_bytes{fstype=~"xfs|ext4"} / node_filesystem_size_bytes{fstype=~"xfs|ext4"} * 100) > 85
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} 磁盘使用率高"
          description: "{{ $labels.instance }} 磁盘使用率高于 85% (当前值: {{ $value }})"
      - alert: "Pod 磁盘使用率高"
        expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) *100 > 85
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} {{ $labels.persistentvolumeclaim }} 磁盘使用率高"
          description: "{{ $labels.instance }} {{ $labels.persistentvolumeclaim }} 磁盘使用率高于 85% (当前值: {{ $value }})"
      # Flink
      - alert: "Flink 任务数增加"
        expr: flink_jobmanager_numRunningJobs{env="prod"} - flink_jobmanager_numRunningJobs{env="prod"} offset 3m > 0
        for: 3m
        labels:
          severity: info
        annotations:
          summary: "Flink 运行任务数相对3分钟前增加了 {{ $value }} 个"
          description: "Flink 运行任务数相对3分钟前增加了 {{ $value }} 个"
      - alert: "Flink 任务数减少"
        expr: flink_jobmanager_numRunningJobs{env="prod"} offset 3m - flink_jobmanager_numRunningJobs{env="prod"} > 0
        for: 3m
        labels:
          severity: info
        annotations:
          summary: "Flink 运行任务数相对3分钟前减少了 {{ $value }} 个"
          description: "Flink 运行任务数相对3分钟前减少了 {{ $value }} 个"
      - alert: "Flink 任务异常"
        expr: absent (flink_jobmanager_numRunningJobs{env="prod"})
        for: 3m
        labels:
          severity: info
        annotations:
          summary: "Flink 任务未正常运行 job: {{$labels.job_name}}"
          description: "Flink 任务未正常运行 job: {{$labels.job_name}}"
      # MySQL
      - alert: "MySQL 慢查询告警"
        expr: irate(mysql_global_status_slow_queries[3m]) * 60 > 30
        for: 3m
        labels:
          severity: info
        annotations:
          summary: "MySQL 慢查询告警，实例: {{$labels.db_instance}}"
          description: "MySQL 一分钟慢查询超过 30 次，实例: {{$labels.db_instance}}"
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 30s
      scrape_timeout: 10s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: kubernetes-pods
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      kubernetes_sd_configs:
      - role: pod
        follow_redirects: true
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      #- action: replace
      #  regex: (https?)
      #  source_labels:
      #  - __meta_kubernetes_pod_annotation_prometheus_io_scheme
      #  target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      #- action: drop
      #  regex: Pending|Succeeded|Failed|Completed
      #  source_labels:
      #  - __meta_kubernetes_pod_phase
      # Reducing Prometheus metrics
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: istio_requests_total
        action: keep
      - source_labels: [__name__]
        regex: "(istio_request_bytes|envoy).+"
        action: drop

    - job_name: kubernetes-pods-slow
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: drop
        regex: Pending|Succeeded|Failed|Completed
        source_labels:
        - __meta_kubernetes_pod_phase
      # Reducing Prometheus metrics
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: istio_requests_total
        action: keep
      - source_labels: [__name__]
        regex: "(istio_request_bytes|envoy).+"
        action: drop
      scrape_interval: 5m
      scrape_timeout: 30s

    - job_name: 'linux'
      scrape_interval: 30s
      static_configs:
      - targets: 
        - 10.32.5.240:9100
        - 10.32.5.240:8080
        labels:
          service: kafka
          env: prod
      - targets: 
        - 10.32.30.55:9100
        labels:
          service: nexus
          env: prod

    - job_name: 'pushgateway'
      scrape_interval: 30s
      static_configs:
      - targets: 
        - pushgateway:9091
        labels:
          service: pushgateway
          env: prod
