serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: default
  namespaceSelector:
    - default
  additionalLabels:
    release: prometheus
  jobLabel: "mysql"
  targetLabels: []
  podTargetLabels: []
  metricRelabelings: []
  # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  relabelings: []
  # Enable multi target scraping.
  multipleTarget:
    enabled: true
    targets:
      # target connection information with name (required), endpoint (required), port (optional), user(optional), password(optional)
      - endpoint: mysql-test
        name: mysql-test
        port: 3306
        user: exporter
        password: exporter
      # - endpoint: mysql2.dns.local
      #   name: mysql2
      #   user: user2
      #   password: password2
    # Enable shared credentials for all targets
# mysql:
#   db: ""
#   host: "mysql"
#   # config my.cnf https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html
#   additionalConfig:
#     # - connect-timeout=5
#     # - debug
#   pass: "exporter"
#   port: 3306
#   protocol: ""
#   user: "exporter"
## 验证：
# ❯ kubectl port-forward service/mysql-exporter-prometheus-mysql-exporter 9104
# ❯ curl 'http://127.0.0.1:9104/probe?auth_module=client.mysql-test&target=mysql-test:3306'
