serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: default
  namespaceSelector:
    - default
  additionalLabels:
    release: prometheus
  jobLabel: "mysql"
  targetLabels: []
  podTargetLabels: []
  metricRelabelings: []
  # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  relabelings: []
  # # Enable multi target scraping.
  # multipleTarget:
  #   enabled: true
  #   targets:
  #     # target connection information with name (required), endpoint (required), port (optional), user(optional), password(optional)
  #     - endpoint: mysql
  #       name: mysql-dev
  #       port: 3306
  #       user: exporter
  #       password: exporter
  #     # - endpoint: mysql2.dns.local
  #     #   name: mysql2
  #     #   user: user2
  #     #   password: password2
  #   # Enable shared credentials for all targets
  #   sharedSecret:
  #     enabled: false
  #     name: ""

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "9104"

# mysql connection params which build the my.cnf config
mysql:
  db: ""
  host: "mysql"
  # config my.cnf https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html
  additionalConfig:
    # - connect-timeout=5
    # - debug
  pass: "exporter"
  port: 3306
  protocol: ""
  user: "exporter"

## Custom PrometheusRules to be defined
## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
prometheusRule:
  enabled: false
  additionalLabels: {}
  namespace: ""
  rules:
    []
    ## These are just examples rules, please adapt them to your needs.
    ## Make sure to constraint the rules to the current service.
    # - alert: MysqlDown
    #   expr: mysql_up == 0
    #   for: 5m
    #   labels:
    #     severity: critical
    #   annotations:
    #     summary: MySQL down (instance {{ $labels.instance }})
    #     description: "MySQL instance is down on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
