# 在 templates 中定义不同场景的 CI 模版，在其中可以自己根据项目来 include 不同的 jobs 。

# ------- 1.导入job模版
include:
  - local: "/jobs/package.yml"
  - local: "/jobs/build.yml"
  - local: "/jobs/deploy.yml"
# ------- 2.定义全局及stage变量
variables:
  GIT_DEPTH: 0
  # 镜像仓库
  CI_REGISTRY_URL: docker-registry-registry-vpc.cn-hangzhou.cr.aliyuncs.com
  CI_REGISTRY_URL_aws: docker-registry-vpc.xx.com

  # CI_REGISTRY_NAMESPACE: cp-frontend 继承具体详项目中的变量
  CI_REGISTRY_IMAGE: $CI_REGISTRY_URL/$CI_REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  CI_REGISTRY_IMAGE_aws: $CI_REGISTRY_URL_aws/$CI_REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  #  CI_REGISTRY_IMAGE: docker-registry-registry-vpc.cn-hangzhou.cr.aliyuncs.com/$CI_REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  CI_REGISTRY_USER: webmaster@xx.cn
  # CI_REGISTRY_PASSWORD: Set in GitLab Project > Settings > CI/CD > Variables
  # 各阶段镜像
  PACKAFGE_IMAGE: docker-registry-registry-vpc.cn-hangzhou.cr.aliyuncs.com/mirror/node:16.3.0-alpine
  BUILD_IMAGE: docker-registry-registry-vpc.cn-hangzhou.cr.aliyuncs.com/mirror/executor:debug
  DEPLOY_IMAGE: docker-registry-registry-vpc.cn-hangzhou.cr.aliyuncs.com/mirror/alpine:3.12-deploy
# ------- 3.配置运行stage

## 更新依赖
.npm-push-dependence:
  script:
    - npm config set registry https://nexus-hz.xx.cn/repository/nmp-group/
    - npm install
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    # policy: push
## 打包
.npm-package:
  script:
    - npm config set registry https://nexus-hz.xx.cn/repository/nmp-group/
    - npm install
    - export CI_ENV=$CI_COMMIT_BRANCH
    - CI_ENV=$(echo $CI_COMMIT_BRANCH | sed 's/-branch-/-/')
    - if [ $CI_COMMIT_BRANCH == "master" ]; then export CI_ENV="prod" ; fi
    - npm run build:$CI_ENV
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - dist
    expire_in: 1 week

stages:
  - package
  - build
  - deploy
# 打包
# package:
#   stage: package
#   image: ${PACKAFGE_IMAGE}
# #  variables:
# #    key: value
#   extends: .package-npm-abroad-platform
#   only:
#     - dev-branch-01
package:
  stage: package
  image: ${PACKAFGE_IMAGE}
  extends: .npm-package
  only:
    - dev-branch-01
# 更新依赖
push_dependence:
  stage: package
  image: ${PACKAFGE_IMAGE}
  extends: .npm-push-dependence
  only:
    refs:
      - dev-branch-01
    changes: # 下面的文件中任一文件发生改变
      - package-lock.json
      - package.json

# 构建镜像
build:
  stage: build
  image: ${BUILD_IMAGE}
  extends: .build-image
  only:
    - dev-branch-01

# 部署
deploy:
  image: ${DEPLOY_IMAGE}
  stage: deploy
  extends: .deploy-h5-test
  only:
    - dev-branch-01
