kind: Service
apiVersion: v1
metadata:
  name: lanling-services
spec:
  selector:
    deployment: lanling-services
  type: ClusterIP
  ports:
  - name: http
    port: 9050
    protocol: TCP
    targetPort: 9050
  - name: http80
    port: 80
    protocol: TCP
    targetPort: 9050