apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-stage
spec:
  destination:
    name: ""
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: Deploys/Projects/istio-bookinfo/overlays/stage
    repoURL: "git@github.com:SJFCS/DevOpsConfig.git"
    targetRevision: HEAD
    plugin:
      name: kustomize-enable-helm
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
