helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 6.6.0
    namespace: argo-cd
    includeCRDs: false
    valuesFile: values.yaml
    additionalValuesFiles:
      - plugin/stage/values.yaml
      # - plugin/kustomize-enable-helm-vaules-custom-image/values.yaml
      # - plugin/argo-vault-plugin-vaules-custom-image/avp-values.yaml
# # kustomize-enable-helm with manifest patch
# configMapGenerator:
#   - name: kustomize-enable-helm
#     namespace: argo-cd
#     files:
#       - plugin/kustomize-enable-helm-manifest-init-containers/plugin.yaml

# generatorOptions:
#   disableNameSuffixHash: true
# patches:
#   - path: plugin/kustomize-enable-helm-manifest-init-containers/argocd-repo-server-deployment-patch.yaml
