# Default values for istio-bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  selector: ingressgateway
  hostname: bookinfo.cloudnative.love

  httpsRedirect: true

  tls:
    enabled: true
    secretName: bookinfo-tls
    gatewayNamespace: istio-system
    acme:
      enabled: true
      certManager:
        version: cert-manager.io/v1
      renewBefore: 720h
      issuerName: cluster-issuer-cloudflare-letsencrypt-prod
      issuerKind: ClusterIssuer

productpage:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi

details:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi

ratings:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi

reviews:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi
