apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: kafka-exporter
  monitor: prometheus

#commonAnnotations:
#  prometheus.io/path: /metrics
#  prometheus.io/port: "9308"
#  prometheus.io/scrape: "true"
#  prometheus.io/scrape-arms: "true"

resources:
  - kafka-exporter.yaml

images:
  - name: danielqsj/kafka-exporter
    newTag: latest
