apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - pvc.yaml
labels:
  - includeSelectors: true
    pairs:
      env: prod
