apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-alert-center-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
