apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-bookinfo
spec:
  destination:
    name: in-cluster
    namespace: default
    server: ""
  source:
    path: "Deploys/Projects/istio-bookinfo/apps"
    repoURL: "git@github.com:SJFCS/DevOpsConfig.git"
    targetRevision: HEAD
  sources: []
  project: default
