apiVersion: v1
data:
    app.conf: |
        server {
            listen 80 default_server;
            server_name dolphinphp.myrightone.com;

            root /app/public;

            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Content-Type-Options "nosniff";

            index index.html index.htm index.php;
            charset utf-8;


            location / {
                if (!-e $request_filename) {
                rewrite  ^/(.*)$  /index.php/$1  last;
                break;
                }
            }


            location = /favicon.ico { access_log off; log_not_found off; }
            location = /robots.txt  { access_log off; log_not_found off; }

            error_page 404 /index.php;


            location ~ \.php(/|$) {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                include        fastcgi.conf;
                set $fastcgi_script_name2 $fastcgi_script_name;
                if ($fastcgi_script_name ~ "^(.+\.php)(/.+)$") {
                    set $fastcgi_script_name2 $1;
                    set $path_info $2;
                }
                fastcgi_param   PATH_INFO $path_info;
                fastcgi_param   SCRIPT_FILENAME   $document_root$fastcgi_script_name2;
                fastcgi_param   SCRIPT_NAME   $fastcgi_script_name2;
            }

            location ~ /\.(?!well-known).* {
                deny all;
            }
        }

    nginx.conf: |
        user  nginx;
        worker_processes  2;

        #error_log  logs/error.log;
        #error_log  logs/error.log  notice;
        #error_log  logs/error.log  info;
        #error_log  /var/log/nginx/error.log warn;

        #pid        logs/nginx.pid;

        events {
            worker_connections  1024;
        }

        http {
            server_names_hash_bucket_size 128;
            server_names_hash_max_size 2056;

            include       mime.types;
            default_type  application/octet-stream;
            server_tokens off;

            log_format  main  '$remote_addr - $remote_user [$time_local] "$host" "$request" $request_time '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

            access_log  /var/log/nginx/access.log main;
            error_log   /var/log/nginx/error.log;

            sendfile        on;
            #tcp_nopush     on;

            #keepalive_timeout  0;
            keepalive_timeout  65;

            #gzip  on;
            gzip on;
            gzip_http_version 1.0;
            gzip_comp_level 2;
            gzip_proxied any;
            gzip_types text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript application/json;
            client_max_body_size 0;

            include docker-sites/*/*.conf;
            include docker-sites/*.conf;
        }
kind: ConfigMap
metadata:
    name: nginx-conf-dolphinphp
