apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphinphp-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: alicloud-nas-subpath
  volumeMode: Filesystem
