helmCharts:
  - name: istio-bookinfo
    releaseName: istio-bookinfo
    # chart: ../../base/charts/example  # 指明 chart 相对路径
    repo: https://SJFCS.github.io/DevOpsConfig
    version: 1.2.3
    namespace: default
    includeCRDs: false
    valuesMerge: override
    valuesFile: values.yaml
