name: Build Images

on:
  push:
    branches:
      - main
    paths:
      - "images/**/Dockerfile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: Images/argo-plugin-sidecar
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        # with:
        #   path: /tmp/.buildx-cache
        #   key: ${{ runner.os }}-buildx-${{ github.sha }}
        #   restore-keys: |
        #     ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Images/${{ matrix.context }}
          file: ./Images/${{ matrix.context }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.context }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context:
#           file: Images/loop/Dockerfile
#           push: true
#           tags: ghcr.io/${{ github.repository_owner }}/Images/loop:${{ github.sha }}
