apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: details
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: productpage
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ratings
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: reviews
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
